// Code generated by protoc-gen-go.
// source: prices.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	prices.proto

It has these top-level messages:
	PricesRequest
	PriceEntry
	PricesResponse
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PricesRequest struct {
	Exchange  string `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	ShortCode string `protobuf:"bytes,2,opt,name=short_code,json=shortCode" json:"short_code,omitempty"`
}

func (m *PricesRequest) Reset()                    { *m = PricesRequest{} }
func (m *PricesRequest) String() string            { return proto.CompactTextString(m) }
func (*PricesRequest) ProtoMessage()               {}
func (*PricesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PricesRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *PricesRequest) GetShortCode() string {
	if m != nil {
		return m.ShortCode
	}
	return ""
}

type PriceEntry struct {
	UnixTimestamp int64 `protobuf:"varint,1,opt,name=unix_timestamp,json=unixTimestamp" json:"unix_timestamp,omitempty"`
	Volume        int64 `protobuf:"varint,2,opt,name=volume" json:"volume,omitempty"`
	Open          int64 `protobuf:"varint,3,opt,name=open" json:"open,omitempty"`
	Close         int64 `protobuf:"varint,4,opt,name=close" json:"close,omitempty"`
	Low           int64 `protobuf:"varint,5,opt,name=low" json:"low,omitempty"`
	High          int64 `protobuf:"varint,6,opt,name=high" json:"high,omitempty"`
}

func (m *PriceEntry) Reset()                    { *m = PriceEntry{} }
func (m *PriceEntry) String() string            { return proto.CompactTextString(m) }
func (*PriceEntry) ProtoMessage()               {}
func (*PriceEntry) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PriceEntry) GetUnixTimestamp() int64 {
	if m != nil {
		return m.UnixTimestamp
	}
	return 0
}

func (m *PriceEntry) GetVolume() int64 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *PriceEntry) GetOpen() int64 {
	if m != nil {
		return m.Open
	}
	return 0
}

func (m *PriceEntry) GetClose() int64 {
	if m != nil {
		return m.Close
	}
	return 0
}

func (m *PriceEntry) GetLow() int64 {
	if m != nil {
		return m.Low
	}
	return 0
}

func (m *PriceEntry) GetHigh() int64 {
	if m != nil {
		return m.High
	}
	return 0
}

type PricesResponse struct {
	Exchange          string        `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	MarketOpenMin     int32         `protobuf:"varint,2,opt,name=market_open_min,json=marketOpenMin" json:"market_open_min,omitempty"`
	MarketCloseMin    int32         `protobuf:"varint,3,opt,name=market_close_min,json=marketCloseMin" json:"market_close_min,omitempty"`
	TimezoneOffsetMin int32         `protobuf:"varint,4,opt,name=timezone_offset_min,json=timezoneOffsetMin" json:"timezone_offset_min,omitempty"`
	PriceIntevalSec   int32         `protobuf:"varint,5,opt,name=price_inteval_sec,json=priceIntevalSec" json:"price_inteval_sec,omitempty"`
	PriceEntries      []*PriceEntry `protobuf:"bytes,6,rep,name=price_entries,json=priceEntries" json:"price_entries,omitempty"`
}

func (m *PricesResponse) Reset()                    { *m = PricesResponse{} }
func (m *PricesResponse) String() string            { return proto.CompactTextString(m) }
func (*PricesResponse) ProtoMessage()               {}
func (*PricesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PricesResponse) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *PricesResponse) GetMarketOpenMin() int32 {
	if m != nil {
		return m.MarketOpenMin
	}
	return 0
}

func (m *PricesResponse) GetMarketCloseMin() int32 {
	if m != nil {
		return m.MarketCloseMin
	}
	return 0
}

func (m *PricesResponse) GetTimezoneOffsetMin() int32 {
	if m != nil {
		return m.TimezoneOffsetMin
	}
	return 0
}

func (m *PricesResponse) GetPriceIntevalSec() int32 {
	if m != nil {
		return m.PriceIntevalSec
	}
	return 0
}

func (m *PricesResponse) GetPriceEntries() []*PriceEntry {
	if m != nil {
		return m.PriceEntries
	}
	return nil
}

func init() {
	proto.RegisterType((*PricesRequest)(nil), "main.PricesRequest")
	proto.RegisterType((*PriceEntry)(nil), "main.PriceEntry")
	proto.RegisterType((*PricesResponse)(nil), "main.PricesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Prices service

type PricesClient interface {
	GetPrices(ctx context.Context, in *PricesRequest, opts ...grpc.CallOption) (*PricesResponse, error)
}

type pricesClient struct {
	cc *grpc.ClientConn
}

func NewPricesClient(cc *grpc.ClientConn) PricesClient {
	return &pricesClient{cc}
}

func (c *pricesClient) GetPrices(ctx context.Context, in *PricesRequest, opts ...grpc.CallOption) (*PricesResponse, error) {
	out := new(PricesResponse)
	err := grpc.Invoke(ctx, "/main.Prices/GetPrices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Prices service

type PricesServer interface {
	GetPrices(context.Context, *PricesRequest) (*PricesResponse, error)
}

func RegisterPricesServer(s *grpc.Server, srv PricesServer) {
	s.RegisterService(&_Prices_serviceDesc, srv)
}

func _Prices_GetPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricesServer).GetPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Prices/GetPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricesServer).GetPrices(ctx, req.(*PricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Prices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Prices",
	HandlerType: (*PricesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrices",
			Handler:    _Prices_GetPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prices.proto",
}

func init() { proto.RegisterFile("prices.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0x4b, 0x6b, 0xdb, 0x40,
	0x10, 0xc7, 0xb1, 0xf5, 0xa0, 0x9e, 0x56, 0x7e, 0xac, 0x4d, 0x11, 0x86, 0x42, 0x31, 0xb4, 0x98,
	0x1e, 0x74, 0x70, 0x69, 0xcf, 0x05, 0x63, 0x4a, 0x02, 0xc1, 0x41, 0xc9, 0x5d, 0x28, 0xca, 0xd8,
	0x5a, 0x22, 0xed, 0x2a, 0xda, 0xb5, 0xe3, 0xe4, 0x5b, 0xe4, 0x9c, 0x2f, 0x1b, 0xed, 0xac, 0x95,
	0xc7, 0x25, 0xb7, 0x99, 0xdf, 0xfc, 0x67, 0x76, 0xe7, 0x01, 0x5f, 0xaa, 0x9a, 0x67, 0xa8, 0xa2,
	0xaa, 0x96, 0x5a, 0x32, 0xb7, 0x4c, 0xb9, 0x98, 0x9d, 0x42, 0x70, 0x4e, 0x34, 0xc6, 0xdb, 0x1d,
	0x2a, 0xcd, 0xa6, 0xf0, 0x09, 0x0f, 0x59, 0x9e, 0x8a, 0x2d, 0x86, 0x9d, 0xef, 0x9d, 0x79, 0x2f,
	0x7e, 0xf1, 0xd9, 0x37, 0x00, 0x95, 0xcb, 0x5a, 0x27, 0x99, 0xbc, 0xc6, 0xb0, 0x4b, 0xd1, 0x1e,
	0x91, 0x65, 0x03, 0x66, 0x4f, 0x1d, 0x00, 0x2a, 0xb6, 0x12, 0xba, 0xbe, 0x67, 0x3f, 0xa0, 0xbf,
	0x13, 0xfc, 0x90, 0x68, 0x5e, 0x36, 0x85, 0xd3, 0xb2, 0xa2, 0x7a, 0x4e, 0x1c, 0x18, 0x7a, 0xd9,
	0x42, 0xf6, 0x15, 0xfc, 0xbd, 0x2c, 0x76, 0xa5, 0x2d, 0xe8, 0xc4, 0x47, 0x8f, 0x31, 0x70, 0x65,
	0x85, 0x22, 0x74, 0x88, 0x92, 0xcd, 0x26, 0xe0, 0x65, 0x85, 0x54, 0x18, 0xba, 0x04, 0xad, 0xc3,
	0x86, 0xe0, 0x14, 0xf2, 0x2e, 0xf4, 0x88, 0x19, 0xd3, 0xe4, 0xe6, 0x7c, 0x9b, 0x87, 0xbe, 0xcd,
	0x35, 0xf6, 0xec, 0xb1, 0x0b, 0xfd, 0xb6, 0x55, 0x55, 0x49, 0xd1, 0x24, 0x7e, 0xd4, 0xeb, 0x4f,
	0x18, 0x94, 0x69, 0x7d, 0x83, 0x3a, 0x31, 0x2f, 0x27, 0x25, 0x17, 0xf4, 0x3f, 0x2f, 0x0e, 0x2c,
	0x5e, 0x37, 0xf4, 0x8c, 0x0b, 0x36, 0x87, 0xe1, 0x51, 0x47, 0x9f, 0x21, 0xa1, 0x43, 0xc2, 0xbe,
	0xe5, 0x4b, 0x83, 0x8d, 0x32, 0x82, 0xb1, 0x19, 0xc5, 0x83, 0x14, 0x98, 0xc8, 0xcd, 0x46, 0x35,
	0x29, 0x46, 0xec, 0x92, 0x78, 0xd4, 0x86, 0xd6, 0x14, 0x31, 0xfa, 0x5f, 0x30, 0xa2, 0x85, 0x25,
	0x5c, 0x68, 0xdc, 0xa7, 0x45, 0xa2, 0x30, 0xa3, 0x26, 0xbd, 0x78, 0x40, 0x81, 0x13, 0xcb, 0x2f,
	0x30, 0x63, 0x7f, 0x20, 0xb0, 0x5a, 0x6c, 0x46, 0xcf, 0x51, 0x35, 0x9d, 0x3b, 0xf3, 0xcf, 0x8b,
	0x61, 0x64, 0x96, 0x1c, 0xbd, 0x2e, 0x25, 0xb6, 0x37, 0xb0, 0xb2, 0xaa, 0xc5, 0x3f, 0xf0, 0xed,
	0x48, 0xd8, 0x5f, 0xe8, 0xfd, 0x47, 0x7d, 0x74, 0xc6, 0x6f, 0xd2, 0xda, 0xc3, 0x98, 0x4e, 0xde,
	0x43, 0x3b, 0xc2, 0x2b, 0x9f, 0x8e, 0xe9, 0xf7, 0x73, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xcc,
	0xd9, 0x71, 0x5c, 0x02, 0x00, 0x00,
}
