// Code generated by protoc-gen-go.
// source: prices.proto
// DO NOT EDIT!

/*
Package main is a generated protocol buffer package.

It is generated from these files:
	prices.proto

It has these top-level messages:
	PricesRequest
	PriceEntries
	PricesResponse
*/
package main

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PricesRequest struct {
	Exchange  string `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	ShortCode string `protobuf:"bytes,2,opt,name=short_code,json=shortCode" json:"short_code,omitempty"`
}

func (m *PricesRequest) Reset()                    { *m = PricesRequest{} }
func (m *PricesRequest) String() string            { return proto.CompactTextString(m) }
func (*PricesRequest) ProtoMessage()               {}
func (*PricesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PricesRequest) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *PricesRequest) GetShortCode() string {
	if m != nil {
		return m.ShortCode
	}
	return ""
}

// / Price entries are formatted this way so that no transform needs to happen
// / on the client side. The charting library accepts this data directly.
type PriceEntries struct {
	UnixTimestamp []int64 `protobuf:"varint,1,rep,packed,name=unix_timestamp,json=unixTimestamp" json:"unix_timestamp,omitempty"`
	Volume        []int64 `protobuf:"varint,2,rep,packed,name=volume" json:"volume,omitempty"`
	// / Array of 4 values per price entry. Open, low, close, high.
	Value []int64 `protobuf:"varint,3,rep,packed,name=value" json:"value,omitempty"`
}

func (m *PriceEntries) Reset()                    { *m = PriceEntries{} }
func (m *PriceEntries) String() string            { return proto.CompactTextString(m) }
func (*PriceEntries) ProtoMessage()               {}
func (*PriceEntries) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PriceEntries) GetUnixTimestamp() []int64 {
	if m != nil {
		return m.UnixTimestamp
	}
	return nil
}

func (m *PriceEntries) GetVolume() []int64 {
	if m != nil {
		return m.Volume
	}
	return nil
}

func (m *PriceEntries) GetValue() []int64 {
	if m != nil {
		return m.Value
	}
	return nil
}

type PricesResponse struct {
	Exchange          string        `protobuf:"bytes,1,opt,name=exchange" json:"exchange,omitempty"`
	MarketOpenMin     int32         `protobuf:"varint,2,opt,name=market_open_min,json=marketOpenMin" json:"market_open_min,omitempty"`
	MarketCloseMin    int32         `protobuf:"varint,3,opt,name=market_close_min,json=marketCloseMin" json:"market_close_min,omitempty"`
	TimezoneOffsetMin int32         `protobuf:"varint,4,opt,name=timezone_offset_min,json=timezoneOffsetMin" json:"timezone_offset_min,omitempty"`
	PriceIntevalSec   int32         `protobuf:"varint,5,opt,name=price_inteval_sec,json=priceIntevalSec" json:"price_inteval_sec,omitempty"`
	PriceEntries      *PriceEntries `protobuf:"bytes,6,opt,name=price_entries,json=priceEntries" json:"price_entries,omitempty"`
}

func (m *PricesResponse) Reset()                    { *m = PricesResponse{} }
func (m *PricesResponse) String() string            { return proto.CompactTextString(m) }
func (*PricesResponse) ProtoMessage()               {}
func (*PricesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PricesResponse) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *PricesResponse) GetMarketOpenMin() int32 {
	if m != nil {
		return m.MarketOpenMin
	}
	return 0
}

func (m *PricesResponse) GetMarketCloseMin() int32 {
	if m != nil {
		return m.MarketCloseMin
	}
	return 0
}

func (m *PricesResponse) GetTimezoneOffsetMin() int32 {
	if m != nil {
		return m.TimezoneOffsetMin
	}
	return 0
}

func (m *PricesResponse) GetPriceIntevalSec() int32 {
	if m != nil {
		return m.PriceIntevalSec
	}
	return 0
}

func (m *PricesResponse) GetPriceEntries() *PriceEntries {
	if m != nil {
		return m.PriceEntries
	}
	return nil
}

func init() {
	proto.RegisterType((*PricesRequest)(nil), "main.PricesRequest")
	proto.RegisterType((*PriceEntries)(nil), "main.PriceEntries")
	proto.RegisterType((*PricesResponse)(nil), "main.PricesResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Prices service

type PricesClient interface {
	GetPrices(ctx context.Context, in *PricesRequest, opts ...grpc.CallOption) (*PricesResponse, error)
}

type pricesClient struct {
	cc *grpc.ClientConn
}

func NewPricesClient(cc *grpc.ClientConn) PricesClient {
	return &pricesClient{cc}
}

func (c *pricesClient) GetPrices(ctx context.Context, in *PricesRequest, opts ...grpc.CallOption) (*PricesResponse, error) {
	out := new(PricesResponse)
	err := grpc.Invoke(ctx, "/main.Prices/GetPrices", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Prices service

type PricesServer interface {
	GetPrices(context.Context, *PricesRequest) (*PricesResponse, error)
}

func RegisterPricesServer(s *grpc.Server, srv PricesServer) {
	s.RegisterService(&_Prices_serviceDesc, srv)
}

func _Prices_GetPrices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PricesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricesServer).GetPrices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/main.Prices/GetPrices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricesServer).GetPrices(ctx, req.(*PricesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Prices_serviceDesc = grpc.ServiceDesc{
	ServiceName: "main.Prices",
	HandlerType: (*PricesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPrices",
			Handler:    _Prices_GetPrices_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "prices.proto",
}

func init() { proto.RegisterFile("prices.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x92, 0x41, 0x4b, 0xeb, 0x40,
	0x10, 0xc7, 0x69, 0xd3, 0x86, 0xd7, 0x79, 0x4d, 0xfb, 0xba, 0x2d, 0x8f, 0x50, 0x10, 0xa4, 0xa0,
	0x14, 0x0f, 0x39, 0x54, 0xd0, 0xab, 0x50, 0x44, 0x14, 0xa4, 0x12, 0xbd, 0x87, 0x18, 0xa7, 0x76,
	0xb1, 0xd9, 0x8d, 0xd9, 0x4d, 0x29, 0x7e, 0x0d, 0xbf, 0xb0, 0xbb, 0xb3, 0x89, 0xd4, 0x8b, 0xc7,
	0xf9, 0xcd, 0x2f, 0xc3, 0xec, 0x7f, 0x02, 0xfd, 0xa2, 0xe4, 0x19, 0xaa, 0xa8, 0x28, 0xa5, 0x96,
	0xac, 0x93, 0xa7, 0x5c, 0xcc, 0xee, 0x20, 0x78, 0x20, 0x1a, 0xe3, 0x7b, 0x85, 0x4a, 0xb3, 0x29,
	0xfc, 0xc1, 0x7d, 0xb6, 0x49, 0xc5, 0x2b, 0x86, 0xad, 0xe3, 0xd6, 0xbc, 0x17, 0x7f, 0xd7, 0xec,
	0x08, 0x40, 0x6d, 0x64, 0xa9, 0x93, 0x4c, 0xbe, 0x60, 0xd8, 0xa6, 0x6e, 0x8f, 0xc8, 0xd2, 0x80,
	0x59, 0x06, 0x7d, 0x9a, 0x75, 0x2d, 0x74, 0xc9, 0x51, 0xb1, 0x13, 0x18, 0x54, 0x82, 0xef, 0x13,
	0xcd, 0x73, 0x33, 0x39, 0xcd, 0x0b, 0x33, 0xd0, 0x9b, 0x7b, 0x71, 0x60, 0xe9, 0x53, 0x03, 0xd9,
	0x7f, 0xf0, 0x77, 0x72, 0x5b, 0xe5, 0x76, 0xa2, 0x6d, 0xd7, 0x15, 0x9b, 0x40, 0x77, 0x97, 0x6e,
	0x2b, 0x0c, 0x3d, 0xc2, 0xae, 0x98, 0x7d, 0xb6, 0x61, 0xd0, 0x6c, 0xac, 0x0a, 0x29, 0x14, 0xfe,
	0xba, 0xf2, 0x29, 0x0c, 0xf3, 0xb4, 0x7c, 0x43, 0x9d, 0xc8, 0x02, 0x45, 0x92, 0x73, 0x41, 0x7b,
	0x77, 0xe3, 0xc0, 0xe1, 0x95, 0xa1, 0xf7, 0x5c, 0xb0, 0x39, 0xfc, 0xab, 0xbd, 0x6c, 0x2b, 0x15,
	0x92, 0xe8, 0x91, 0x38, 0x70, 0x7c, 0x69, 0xb1, 0x35, 0x23, 0x18, 0xdb, 0x07, 0x7d, 0x48, 0x81,
	0x89, 0x5c, 0xaf, 0x95, 0xf9, 0xc4, 0xca, 0x1d, 0x92, 0x47, 0x4d, 0x6b, 0x45, 0x1d, 0xeb, 0x9f,
	0xc1, 0x88, 0x72, 0x4f, 0xb8, 0xd0, 0x68, 0xde, 0x90, 0x28, 0xcc, 0xc2, 0x2e, 0xd9, 0x43, 0x6a,
	0xdc, 0x3a, 0xfe, 0x88, 0x19, 0xbb, 0x84, 0xc0, 0xb9, 0xe8, 0x22, 0x0c, 0x7d, 0xe3, 0xfd, 0x5d,
	0xb0, 0xc8, 0xde, 0x2a, 0x3a, 0x0c, 0x37, 0x76, 0xc7, 0xac, 0xab, 0xc5, 0x15, 0xf8, 0x2e, 0x14,
	0x76, 0x01, 0xbd, 0x1b, 0xd4, 0x75, 0x31, 0x3e, 0xf8, 0xb0, 0xb9, 0xf0, 0x74, 0xf2, 0x13, 0xba,
	0x10, 0x9f, 0x7d, 0xfa, 0x2b, 0xce, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc7, 0x96, 0x33, 0x25,
	0x25, 0x02, 0x00, 0x00,
}
